---
- name: Add Sublime GPG apt Key
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Add Sublime Repository
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    state: present

- name: Install required packages
  apt:
    pkg:
      - apt-transport-https
    state: latest
    update_cache: true

- name: Install Sublime
  apt:
    name: sublime-text
    state: latest
